blueprint:
  name: Intelligente Lichtsteuerung
  description: Flexible Steuerung einer Ziel-Lampe durch Bewegungsmelder, Quell-Lampe (optional), Nachtmodus und andere Optionen.
  domain: automation
  input:
    target_light:
      name: Ziel-Lampe
      description: Die Lampe, die gesteuert werden soll.
      selector:
        entity:
          domain: light

    motion_sensor:
      name: Bewegungsmelder
      description: Der Bewegungsmelder, der die Ziel-Lampe im Bewegungsmodus steuert.
      selector:
        entity:
          domain: binary_sensor
          device_class: motion

    motion_light_brightness:
      name: Helligkeit (Bewegungsmelder-Modus)
      description: Helligkeit der Ziel-Lampe im Bewegungsmodus (in %).
      default: 100
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"

    motion_light_color_temp:
      name: Farbtemperatur (Bewegungsmelder-Modus)
      description: Farbtemperatur der Ziel-Lampe im Bewegungsmodus.
      default: 274
      selector:
        number:
          min: 153
          max: 500

    motion_light_duration:
      name: Dauer (Bewegungsmelder-Modus)
      description: Zeit in Sekunden, wie lange die Lampe eingeschaltet bleibt, wenn keine Bewegung mehr erkannt wird.
      default: 60
      selector:
        number:
          min: 1
          max: 3600
          unit_of_measurement: seconds

    sync_with_source:
      name: Kopieren der Quell-Lampe aktivieren
      description: Soll die Ziel-Lampe die Einstellungen der Quell-Lampe übernehmen?
      default: false
      selector:
        boolean: {}

    source_light:
      name: Quell-Lampe (optional)
      description: Die Lampe, deren Status und Einstellungen kopiert werden sollen.
      selector:
        entity:
          domain: light

    enable_night_mode:
      name: Nachtmodus aktivieren
      description: Soll der Nachtmodus aktiviert werden?
      default: false
      selector:
        boolean: {}

    night_mode_color:
      name: Farbe (Nachtmodus)
      description: Farbe der Ziel-Lampe im Nachtmodus.
      default: [255, 153, 0]
      selector:
        color_rgb: {}

    night_mode_brightness:
      name: Helligkeit (Nachtmodus)
      description: Helligkeit der Ziel-Lampe im Nachtmodus (in %).
      default: 30
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"

    night_mode_start:
      name: Nachtmodus Startzeit
      description: Uhrzeit, ab wann der Nachtmodus aktiv sein soll.
      default: "22:00:00"
      selector:
        time: {}

    night_mode_end:
      name: Nachtmodus Endzeit
      description: Uhrzeit, bis wann der Nachtmodus aktiv sein soll.
      default: "06:00:00"
      selector:
        time: {}

trigger:
  - platform: state
    entity_id: !input motion_sensor
  - platform: state
    entity_id: !input source_light

variables:
  target_light: !input target_light
  motion_sensor: !input motion_sensor
  motion_light_brightness: !input motion_light_brightness
  motion_light_color_temp: !input motion_light_color_temp
  motion_light_duration: !input motion_light_duration
  enable_night_mode: !input enable_night_mode
  night_mode_color: !input night_mode_color
  night_mode_brightness: !input night_mode_brightness
  night_mode_start: !input night_mode_start
  night_mode_end: !input night_mode_end
  sync_with_source: !input sync_with_source
  source_light: !input source_light if !input sync_with_source else null

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ sync_with_source and source_light and is_state(source_light, 'on') }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input target_light
            data:
              brightness: "{{ state_attr(source_light, 'brightness') }}"
              rgb_color: "{{ state_attr(source_light, 'rgb_color') }}"

      - conditions:
          - condition: template
            value_template: "{{ not sync_with_source or (source_light and is_state(source_light, 'off')) }}"
          - condition: state
            entity_id: !input motion_sensor
            state: "on"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input target_light
            data:
              brightness_pct: !input motion_light_brightness
              color_temp: !input motion_light_color_temp
          - wait_for_trigger:
              - platform: state
                entity_id: !input motion_sensor
                to: "off"
            timeout: !input motion_light_duration
            continue_on_timeout: true
          - choose:
              - conditions:
                  - condition: state
                    entity_id: !input motion_sensor
                    state: "off"
                sequence:
                  - service: light.turn_off
                    target:
                      entity_id: !input target_light

    default:
      - service: light.turn_off
        target:
          entity_id: !input target_light

mode: restart
